### ISSUE TITLE
Why always use bottleneck?

### ISSUE THREAD

**Issue by twmht** [jhkim89/PyramidNet#2]
in resnet-34, the block is basicBlock.

but in the code, you always use bottleneck (https://github.com/jhkim89/PyramidNet/blob/master/addpyramidnet.lua#L125), do we also need bottleneck when using resnet-34?

**Comment by jhkim89** [comment]
ResNet uses basicblock when it has 34 layers, and there is a mistake in the code.
We will fix the code to use basicblock when 34 layers.
You may temporarily fix the code from bottleneck to basicblock when you train 34 layers.

**Comment by twmht** [comment]
@jhkim89 

ok
