### ISSUE TITLE
the basic layer is different from resnet

### ISSUE THREAD

**Issue by twmht** [jhkim89/PyramidNet#3]
in resnet basic block, there is no bn in the head (https://github.com/facebook/fb.resnet.torch/blob/master/models/resnet.lua#L53)

Is there any reason to add bn in the head of the basic block in PyramidNet  (https://github.com/jhkim89/PyramidNet/blob/master/addpyramidnet.lua#L53)?

**Comment by jhkim89** [comment]
The detail of using bn in the head of block is described at this paper.
(https://arxiv.org/abs/1603.05027)
You can refer to their code below:
https://github.com/facebook/fb.resnet.torch/blob/master/models/preresnet.lua
and you can find that they are using bn in the head. (L69)
About the detail of our network, please refer to our paper.

**Comment by twmht** [comment]
@jhkim89 

ok. I thought the basic block is identical with resnet34, but with pyramid structure. this is my mistake.
